
services:
  # ==========================================
  # [Infrastructure]
  # ==========================================

  # Mysql 삭제

#  redis:
#    image: redis:7
#    container_name: billing-redis
#    ports:
#      - "6379:6379"
#    networks:
#      - billing-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: billing-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - billing-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: billing-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - billing-net

  # ==========================================
  # [Applications]
  # ==========================================

  billing-api:
    build:
      context: .
      dockerfile: billing_api/Dockerfile
    container_name: billing-api
    ports:
      - "8080:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:13306/batch
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

    networks:
      - billing-net

  billing-batch:
    build:
      context: .
      dockerfile: billing_batch/Dockerfile
    container_name: billing-batch
    ports:
      - "8081:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:13306/batch
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_started
    networks:
      - billing-net

  billing-message:
    build:
      context: .
      dockerfile: billing_message/Dockerfile
    container_name: billing-message
    ports:
      - "8082:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:13306/message
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092

    depends_on:
      kafka:
        condition: service_started

    networks:
      - billing-net

networks:
  billing-net:
    driver: bridge
